-- Generated from control/generated/mixer-schema.json; do not edit.
return {
  version = "1.1.0",
  controls = {
    {key = "master", label = "Master level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel0", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel1", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel2", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel3", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel4", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel5", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel6", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel7", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "input0Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input0Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input0Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input0Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source0Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source0Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source0Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source0HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source0HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source0Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input1Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input1Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input1Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input1Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source1Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source1Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source1Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source1HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source1HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source1Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input2Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input2Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input2Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input2Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source2Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source2Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source2Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source2HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source2HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source2Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input3Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input3Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input3Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input3Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source3Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source3Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source3Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source3HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source3HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source3Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input4Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input4Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input4Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input4Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source4Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source4Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source4Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source4HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source4HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source4Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input5Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input5Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input5Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input5Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source5Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source5Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source5Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source5HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source5HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source5Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input6Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input6Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input6Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input6Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source6Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source6Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source6Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source6HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source6HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source6Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input7Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input7Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input7Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input7Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source7Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source7Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source7Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source7HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source7HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source7Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input8Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input8Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input8Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input8Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source8Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source8Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source8Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source8HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source8HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source8Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input9Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input9Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input9Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input9Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source9Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source9Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source9Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source9HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source9HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source9Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input10Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input10Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input10Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input10Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source10Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source10Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source10Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source10HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source10HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source10Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input11Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input11Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input11Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input11Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source11Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source11Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source11Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source11HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source11HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source11Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input12Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input12Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input12Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input12Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source12Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source12Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source12Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source12HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source12HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source12Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input13Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input13Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input13Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input13Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source13Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source13Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source13Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source13HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source13HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source13Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input14Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input14Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input14Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input14Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source14Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source14Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source14Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source14HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source14HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source14Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input15Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input15Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input15Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input15Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source15Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source15Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source15Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source15HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source15HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source15Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
  },
  pages = {
    {label = "MASTER", controls = {"master"}},
    {label = "KICK", controls = {"groupLevel0"}},
    {label = "DRUMS", controls = {"groupLevel1"}},
    {label = "BASS", controls = {"groupLevel2"}},
    {label = "MUSIC_A", controls = {"groupLevel3"}},
    {label = "MUSIC_B", controls = {"groupLevel4"}},
    {label = "VOCALS", controls = {"groupLevel5"}},
    {label = "FX_A", controls = {"groupLevel6"}},
    {label = "FX_B", controls = {"groupLevel7"}},
    {label = "INPUT 1: drums_1", controls = {"input0Group", "input0Partner", "input0Mode", "input0Orientation", "source0Trim", "source0Mute", "source0Polarity", "source0HPF", "source0HPFHz", "source0Pan"}},
    {label = "INPUT 2: drums_2", controls = {"input1Group", "input1Partner", "input1Mode", "input1Orientation", "source1Trim", "source1Mute", "source1Polarity", "source1HPF", "source1HPFHz", "source1Pan"}},
    {label = "INPUT 3: drums_3", controls = {"input2Group", "input2Partner", "input2Mode", "input2Orientation", "source2Trim", "source2Mute", "source2Polarity", "source2HPF", "source2HPFHz", "source2Pan"}},
    {label = "INPUT 4: drums_4", controls = {"input3Group", "input3Partner", "input3Mode", "input3Orientation", "source3Trim", "source3Mute", "source3Polarity", "source3HPF", "source3HPFHz", "source3Pan"}},
    {label = "INPUT 5: bass", controls = {"input4Group", "input4Partner", "input4Mode", "input4Orientation", "source4Trim", "source4Mute", "source4Polarity", "source4HPF", "source4HPFHz", "source4Pan"}},
    {label = "INPUT 6: instruments_1", controls = {"input5Group", "input5Partner", "input5Mode", "input5Orientation", "source5Trim", "source5Mute", "source5Polarity", "source5HPF", "source5HPFHz", "source5Pan"}},
    {label = "INPUT 7: instruments_2", controls = {"input6Group", "input6Partner", "input6Mode", "input6Orientation", "source6Trim", "source6Mute", "source6Polarity", "source6HPF", "source6HPFHz", "source6Pan"}},
    {label = "INPUT 8: instruments_3", controls = {"input7Group", "input7Partner", "input7Mode", "input7Orientation", "source7Trim", "source7Mute", "source7Polarity", "source7HPF", "source7HPFHz", "source7Pan"}},
    {label = "INPUT 9: instruments_4", controls = {"input8Group", "input8Partner", "input8Mode", "input8Orientation", "source8Trim", "source8Mute", "source8Polarity", "source8HPF", "source8HPFHz", "source8Pan"}},
    {label = "INPUT 10: vocals_1", controls = {"input9Group", "input9Partner", "input9Mode", "input9Orientation", "source9Trim", "source9Mute", "source9Polarity", "source9HPF", "source9HPFHz", "source9Pan"}},
    {label = "INPUT 11: vocals_2", controls = {"input10Group", "input10Partner", "input10Mode", "input10Orientation", "source10Trim", "source10Mute", "source10Polarity", "source10HPF", "source10HPFHz", "source10Pan"}},
    {label = "INPUT 12: vocals_3", controls = {"input11Group", "input11Partner", "input11Mode", "input11Orientation", "source11Trim", "source11Mute", "source11Polarity", "source11HPF", "source11HPFHz", "source11Pan"}},
    {label = "INPUT 13: fx_return_1", controls = {"input12Group", "input12Partner", "input12Mode", "input12Orientation", "source12Trim", "source12Mute", "source12Polarity", "source12HPF", "source12HPFHz", "source12Pan"}},
    {label = "INPUT 14: fx_return_2", controls = {"input13Group", "input13Partner", "input13Mode", "input13Orientation", "source13Trim", "source13Mute", "source13Polarity", "source13HPF", "source13HPFHz", "source13Pan"}},
    {label = "INPUT 15: fx_return_3", controls = {"input14Group", "input14Partner", "input14Mode", "input14Orientation", "source14Trim", "source14Mute", "source14Polarity", "source14HPF", "source14HPFHz", "source14Pan"}},
    {label = "INPUT 16: fx_return_4", controls = {"input15Group", "input15Partner", "input15Mode", "input15Orientation", "source15Trim", "source15Mute", "source15Polarity", "source15HPF", "source15HPFHz", "source15Pan"}},
  }
}
