-- Generated from control/generated/mixer-schema.json; do not edit.
return {
  version = "1.1.0",
  controls = {
    {key = "master", label = "Master level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel0", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel1", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel2", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel3", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel4", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel5", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel6", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "groupLevel7", label = "Level", kind = "db", min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "source0Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source0Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source0Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source0HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source0HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source0Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source1Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source1Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source1Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source1HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source1HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source1Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source2Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source2Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source2Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source2HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source2HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source2Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source3Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source3Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source3Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source3HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source3HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source3Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source4Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source4Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source4Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source4HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source4HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source4Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source5Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source5Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source5Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source5HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source5HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source5Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source6Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source6Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source6Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source6HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source6HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source6Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source7Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source7Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source7Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source7HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source7HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source7Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source8Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source8Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source8Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source8HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source8HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source8Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source9Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source9Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source9Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source9HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source9HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source9Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source10Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source10Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source10Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source10HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source10HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source10Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source11Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source11Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source11Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source11HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source11HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source11Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source12Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source12Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source12Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source12HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source12HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source12Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source13Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source13Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source13Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source13HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source13HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source13Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source14Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source14Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source14Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source14HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source14HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source14Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
    {key = "source15Trim", label = "Trim", kind = "db", min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source15Mute", label = "Mute", kind = "boolean", values = {0, 1}},
    {key = "source15Polarity", label = "Polarity", kind = "enum", values = {-1, 1}},
    {key = "source15HPF", label = "HPF", kind = "boolean", values = {0, 1}},
    {key = "source15HPFHz", label = "HPF cutoff", kind = "frequency", min = 20, max = 20000, step = 1},
    {key = "source15Pan", label = "Pan", kind = "normalized", min = -1, max = 1, step = 0.01},
  },
  pages = {
    {label = "MASTER", controls = {"master"}},
    {label = "KICK", controls = {"groupLevel0"}},
    {label = "DRUMS", controls = {"groupLevel1"}},
    {label = "BASS", controls = {"groupLevel2"}},
    {label = "MUSIC_A", controls = {"groupLevel3"}},
    {label = "MUSIC_B", controls = {"groupLevel4"}},
    {label = "VOCALS", controls = {"groupLevel5"}},
    {label = "FX_A", controls = {"groupLevel6"}},
    {label = "FX_B", controls = {"groupLevel7"}},
    {label = "DRUMS_1", controls = {"source0Trim", "source0Mute", "source0Polarity", "source0HPF", "source0HPFHz", "source0Pan"}},
    {label = "DRUMS_2", controls = {"source1Trim", "source1Mute", "source1Polarity", "source1HPF", "source1HPFHz", "source1Pan"}},
    {label = "DRUMS_3", controls = {"source2Trim", "source2Mute", "source2Polarity", "source2HPF", "source2HPFHz", "source2Pan"}},
    {label = "DRUMS_4", controls = {"source3Trim", "source3Mute", "source3Polarity", "source3HPF", "source3HPFHz", "source3Pan"}},
    {label = "BASS", controls = {"source4Trim", "source4Mute", "source4Polarity", "source4HPF", "source4HPFHz", "source4Pan"}},
    {label = "INSTRUMENTS_1", controls = {"source5Trim", "source5Mute", "source5Polarity", "source5HPF", "source5HPFHz", "source5Pan"}},
    {label = "INSTRUMENTS_2", controls = {"source6Trim", "source6Mute", "source6Polarity", "source6HPF", "source6HPFHz", "source6Pan"}},
    {label = "INSTRUMENTS_3", controls = {"source7Trim", "source7Mute", "source7Polarity", "source7HPF", "source7HPFHz", "source7Pan"}},
    {label = "INSTRUMENTS_4", controls = {"source8Trim", "source8Mute", "source8Polarity", "source8HPF", "source8HPFHz", "source8Pan"}},
    {label = "VOCALS_1", controls = {"source9Trim", "source9Mute", "source9Polarity", "source9HPF", "source9HPFHz", "source9Pan"}},
    {label = "VOCALS_2", controls = {"source10Trim", "source10Mute", "source10Polarity", "source10HPF", "source10HPFHz", "source10Pan"}},
    {label = "VOCALS_3", controls = {"source11Trim", "source11Mute", "source11Polarity", "source11HPF", "source11HPFHz", "source11Pan"}},
    {label = "FX_RETURN_1", controls = {"source12Trim", "source12Mute", "source12Polarity", "source12HPF", "source12HPFHz", "source12Pan"}},
    {label = "FX_RETURN_2", controls = {"source13Trim", "source13Mute", "source13Polarity", "source13HPF", "source13HPFHz", "source13Pan"}},
    {label = "FX_RETURN_3", controls = {"source14Trim", "source14Mute", "source14Polarity", "source14HPF", "source14HPFHz", "source14Pan"}},
    {label = "FX_RETURN_4", controls = {"source15Trim", "source15Mute", "source15Polarity", "source15HPF", "source15HPFHz", "source15Pan"}},
  }
}
