-- Generated from control/generated/mixer-schema.json; do not edit.
return {
  version = "1.2.0",
  controls = {
    {key = "master", label = "Master", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "masterPanicMute", label = "Panic mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "masterEqBypass", label = "Master EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "masterEqDb", label = "Master broad EQ dB", kind = "normalized", writable = true, min = -6, max = 6, step = 0.01},
    {key = "groupLevel0", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group0PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.5, max = 0.5, step = 0.01},
    {key = "group0PosY", label = "Y", kind = "normalized", writable = true, min = 1.0, max = 1.0, step = 0.01},
    {key = "group0Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 0.0, step = 0.01},
    {key = "group0SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group0Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group0EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group0EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group0EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group0EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group0EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group0EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group0EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group0EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group0EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group0CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group0CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group0CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group0CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group0CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group0SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group0SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group0DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group0DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group0DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group0DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "groupLevel1", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group1PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.25, max = 0.75, step = 0.01},
    {key = "group1PosY", label = "Y", kind = "normalized", writable = true, min = 0.5, max = 1.0, step = 0.01},
    {key = "group1Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 0.75, step = 0.01},
    {key = "group1SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group1Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group1EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group1EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group1EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group1EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group1EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group1EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group1EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group1EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group1EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group1CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group1CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group1CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group1CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group1CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group1SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group1SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group1DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group1DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group1DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group1DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "groupLevel2", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group2PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.5, max = 0.5, step = 0.01},
    {key = "group2PosY", label = "Y", kind = "normalized", writable = true, min = 1.0, max = 1.0, step = 0.01},
    {key = "group2Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 0.0, step = 0.01},
    {key = "group2SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group2Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group2EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group2EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group2EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group2EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group2EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group2EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group2EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group2EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group2EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group2CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group2CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group2CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group2CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group2CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group2SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group2SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group2DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group2DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group2DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group2DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "groupLevel3", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group3PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group3PosY", label = "Y", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group3Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group3SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group3Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group3EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group3EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group3EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group3EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group3EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group3EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group3EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group3EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group3EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group3CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group3CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group3CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group3CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group3CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group3SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group3SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group3DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group3DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group3DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group3DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "groupLevel4", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group4PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group4PosY", label = "Y", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group4Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group4SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group4Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group4EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group4EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group4EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group4EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group4EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group4EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group4EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group4EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group4EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group4CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group4CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group4CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group4CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group4CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group4SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group4SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group4DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group4DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group4DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group4DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "groupLevel5", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group5PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.25, max = 0.75, step = 0.01},
    {key = "group5PosY", label = "Y", kind = "normalized", writable = true, min = 0.5, max = 1.0, step = 0.01},
    {key = "group5Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 0.5, step = 0.01},
    {key = "group5SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group5Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group5EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group5EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group5EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group5EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group5EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group5EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group5EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group5EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group5EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group5CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group5CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group5CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group5CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group5CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group5SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group5SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group5DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group5DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group5DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group5DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "groupLevel6", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group6PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group6PosY", label = "Y", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group6Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group6SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group6Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group6EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group6EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group6EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group6EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group6EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group6EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group6EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group6EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group6EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group6CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group6CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group6CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group6CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group6CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group6SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group6SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group6DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group6DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group6DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group6DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "groupLevel7", label = "Level", kind = "db", writable = true, min = -120.0, max = 6.020599913279624, step = 0.5},
    {key = "group7PosX", label = "Stereo X / pan", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group7PosY", label = "Y", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group7Width", label = "Width", kind = "normalized", writable = true, min = 0.0, max = 1.0, step = 0.01},
    {key = "group7SpatialBypass", label = "Spatial bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group7Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group7EqBypass", label = "EQ bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group7EqLowDb", label = "EQ low shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group7EqLowHz", label = "EQ low shelf Hz", kind = "frequency", writable = true, min = 40, max = 500, step = 1},
    {key = "group7EqLowMidDb", label = "EQ low-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group7EqLowMidHz", label = "EQ low-mid Hz", kind = "frequency", writable = true, min = 100, max = 2000, step = 1},
    {key = "group7EqHighMidDb", label = "EQ high-mid dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group7EqHighMidHz", label = "EQ high-mid Hz", kind = "frequency", writable = true, min = 500, max = 8000, step = 1},
    {key = "group7EqHighDb", label = "EQ high shelf dB", kind = "normalized", writable = true, min = -12, max = 12, step = 0.01},
    {key = "group7EqHighHz", label = "EQ high shelf Hz", kind = "frequency", writable = true, min = 2000, max = 16000, step = 1},
    {key = "group7CompBypass", label = "Compressor bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group7CompThresholdDb", label = "Compressor threshold dB", kind = "normalized", writable = true, min = -60, max = 0, step = 0.01},
    {key = "group7CompRatio", label = "Compressor ratio", kind = "normalized", writable = true, min = 1, max = 20, step = 0.01},
    {key = "group7CompAttack", label = "Compressor attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group7CompRelease", label = "Compressor release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "group7SatBypass", label = "Saturation bypass", kind = "boolean", writable = true, values = {0, 1}},
    {key = "group7SatDrive", label = "Saturation drive", kind = "normalized", writable = true, min = 1, max = 4, step = 0.01},
    {key = "group7DuckAmountDb", label = "Kick duck amount dB", kind = "normalized", writable = true, min = 0, max = 18, step = 0.01},
    {key = "group7DuckThreshold", label = "Kick detector threshold", kind = "normalized", writable = true, min = 0.001, max = 1, step = 0.01},
    {key = "group7DuckAttack", label = "Duck attack seconds", kind = "normalized", writable = true, min = 0.001, max = 0.5, step = 0.01},
    {key = "group7DuckRelease", label = "Duck release seconds", kind = "normalized", writable = true, min = 0.01, max = 2, step = 0.01},
    {key = "recordStart", label = "Start new recording", kind = "boolean", writable = true, values = {0, 1}},
    {key = "recordStop", label = "Stop recording", kind = "boolean", writable = true, values = {0, 1}},
    {key = "recorderState", label = "Recorder state", kind = "string", writable = false, values = {"IDLE", "READY", "RECORDING", "LOW_SPACE", "FINAL_SEGMENT", "STOPPED_FULL", "NO_RECORDING_DISK", "DISK_LOST", "FAILED"}},
    {key = "recorderElapsedSeconds", label = "Elapsed seconds", kind = "normalized", writable = false, min = 0, max = 86400, step = 0.01},
    {key = "recorderSegment", label = "Current segment", kind = "normalized", writable = false, min = -1, max = 10000, step = 0.01},
    {key = "recorderRemainingSeconds", label = "Estimated remaining seconds", kind = "normalized", writable = false, min = 0, max = 31536000, step = 0.01},
    {key = "recorderDiskFreeBytes", label = "Recording disk free bytes", kind = "normalized", writable = false, min = 0, max = 9000000000000000, step = 0.01},
    {key = "recorderDroppedFrames", label = "Dropped audio frames", kind = "normalized", writable = false, min = 0, max = 9000000000000000, step = 0.01},
    {key = "recorderError", label = "Recorder error", kind = "string", writable = false, values = {""}},
    {key = "testGeneratorEnable", label = "Enable test generator", kind = "boolean", writable = true, values = {0, 1}},
    {key = "testGeneratorArm", label = "Arm test generator (10 seconds)", kind = "boolean", writable = true, values = {0, 1}},
    {key = "testGeneratorLevelDb", label = "Test generator level dBFS", kind = "normalized", writable = true, min = -60, max = -30, step = 0.01},
    {key = "testGeneratorType", label = "Test signal", kind = "enum", writable = true, values = {0, 1, 2}},
    {key = "testGeneratorDestination", label = "Test destination group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input0Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input0Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input0Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input0Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source0Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source0Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source0Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source0HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source0HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source0Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input1Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input1Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input1Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input1Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source1Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source1Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source1Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source1HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source1HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source1Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input2Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input2Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input2Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input2Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source2Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source2Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source2Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source2HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source2HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source2Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input3Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input3Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input3Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input3Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source3Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source3Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source3Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source3HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source3HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source3Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input4Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input4Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input4Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input4Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source4Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source4Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source4Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source4HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source4HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source4Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input5Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input5Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input5Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input5Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source5Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source5Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source5Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source5HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source5HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source5Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input6Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input6Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input6Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input6Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source6Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source6Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source6Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source6HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source6HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source6Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input7Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input7Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input7Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input7Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source7Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source7Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source7Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source7HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source7HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source7Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input8Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input8Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input8Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input8Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source8Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source8Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source8Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source8HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source8HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source8Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input9Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input9Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input9Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input9Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source9Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source9Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source9Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source9HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source9HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source9Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input10Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input10Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input10Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input10Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source10Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source10Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source10Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source10HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source10HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source10Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input11Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input11Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input11Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input11Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source11Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source11Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source11Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source11HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source11HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source11Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input12Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input12Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input12Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input12Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source12Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source12Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source12Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source12HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source12HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source12Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input13Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input13Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input13Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input13Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source13Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source13Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source13Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source13HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source13HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source13Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input14Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input14Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input14Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input14Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source14Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source14Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source14Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source14HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source14HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source14Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
    {key = "input15Group", label = "Assigned group", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7}},
    {key = "input15Partner", label = "Stereo partner", kind = "enum", writable = true, values = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}},
    {key = "input15Mode", label = "Mode", kind = "enum", writable = false, values = {0, 1}},
    {key = "input15Orientation", label = "Stereo orientation", kind = "enum", writable = false, values = {0, 1, 2}},
    {key = "source15Trim", label = "Trim", kind = "db", writable = true, min = -80.0, max = 12.041199826559248, step = 0.5},
    {key = "source15Mute", label = "Mute", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source15Polarity", label = "Polarity", kind = "enum", writable = true, values = {-1, 1}},
    {key = "source15HPF", label = "HPF", kind = "boolean", writable = true, values = {0, 1}},
    {key = "source15HPFHz", label = "HPF cutoff", kind = "frequency", writable = true, min = 20, max = 20000, step = 1},
    {key = "source15Pan", label = "Pan", kind = "normalized", writable = true, min = -1, max = 1, step = 0.01},
  },
  pages = {
    {label = "MASTER", controls = {"master", "masterPanicMute", "masterEqBypass", "masterEqDb"}},
    {label = "KICK", controls = {"groupLevel0", "group0PosX", "group0PosY", "group0Width", "group0SpatialBypass", "group0Mute", "group0EqBypass", "group0EqLowDb", "group0EqLowHz", "group0EqLowMidDb", "group0EqLowMidHz", "group0EqHighMidDb", "group0EqHighMidHz", "group0EqHighDb", "group0EqHighHz", "group0CompBypass", "group0CompThresholdDb", "group0CompRatio", "group0CompAttack", "group0CompRelease", "group0SatBypass", "group0SatDrive", "group0DuckAmountDb", "group0DuckThreshold", "group0DuckAttack", "group0DuckRelease"}},
    {label = "DRUMS", controls = {"groupLevel1", "group1PosX", "group1PosY", "group1Width", "group1SpatialBypass", "group1Mute", "group1EqBypass", "group1EqLowDb", "group1EqLowHz", "group1EqLowMidDb", "group1EqLowMidHz", "group1EqHighMidDb", "group1EqHighMidHz", "group1EqHighDb", "group1EqHighHz", "group1CompBypass", "group1CompThresholdDb", "group1CompRatio", "group1CompAttack", "group1CompRelease", "group1SatBypass", "group1SatDrive", "group1DuckAmountDb", "group1DuckThreshold", "group1DuckAttack", "group1DuckRelease"}},
    {label = "BASS", controls = {"groupLevel2", "group2PosX", "group2PosY", "group2Width", "group2SpatialBypass", "group2Mute", "group2EqBypass", "group2EqLowDb", "group2EqLowHz", "group2EqLowMidDb", "group2EqLowMidHz", "group2EqHighMidDb", "group2EqHighMidHz", "group2EqHighDb", "group2EqHighHz", "group2CompBypass", "group2CompThresholdDb", "group2CompRatio", "group2CompAttack", "group2CompRelease", "group2SatBypass", "group2SatDrive", "group2DuckAmountDb", "group2DuckThreshold", "group2DuckAttack", "group2DuckRelease"}},
    {label = "MUSIC_A", controls = {"groupLevel3", "group3PosX", "group3PosY", "group3Width", "group3SpatialBypass", "group3Mute", "group3EqBypass", "group3EqLowDb", "group3EqLowHz", "group3EqLowMidDb", "group3EqLowMidHz", "group3EqHighMidDb", "group3EqHighMidHz", "group3EqHighDb", "group3EqHighHz", "group3CompBypass", "group3CompThresholdDb", "group3CompRatio", "group3CompAttack", "group3CompRelease", "group3SatBypass", "group3SatDrive", "group3DuckAmountDb", "group3DuckThreshold", "group3DuckAttack", "group3DuckRelease"}},
    {label = "MUSIC_B", controls = {"groupLevel4", "group4PosX", "group4PosY", "group4Width", "group4SpatialBypass", "group4Mute", "group4EqBypass", "group4EqLowDb", "group4EqLowHz", "group4EqLowMidDb", "group4EqLowMidHz", "group4EqHighMidDb", "group4EqHighMidHz", "group4EqHighDb", "group4EqHighHz", "group4CompBypass", "group4CompThresholdDb", "group4CompRatio", "group4CompAttack", "group4CompRelease", "group4SatBypass", "group4SatDrive", "group4DuckAmountDb", "group4DuckThreshold", "group4DuckAttack", "group4DuckRelease"}},
    {label = "VOCALS", controls = {"groupLevel5", "group5PosX", "group5PosY", "group5Width", "group5SpatialBypass", "group5Mute", "group5EqBypass", "group5EqLowDb", "group5EqLowHz", "group5EqLowMidDb", "group5EqLowMidHz", "group5EqHighMidDb", "group5EqHighMidHz", "group5EqHighDb", "group5EqHighHz", "group5CompBypass", "group5CompThresholdDb", "group5CompRatio", "group5CompAttack", "group5CompRelease", "group5SatBypass", "group5SatDrive", "group5DuckAmountDb", "group5DuckThreshold", "group5DuckAttack", "group5DuckRelease"}},
    {label = "FX_A", controls = {"groupLevel6", "group6PosX", "group6PosY", "group6Width", "group6SpatialBypass", "group6Mute", "group6EqBypass", "group6EqLowDb", "group6EqLowHz", "group6EqLowMidDb", "group6EqLowMidHz", "group6EqHighMidDb", "group6EqHighMidHz", "group6EqHighDb", "group6EqHighHz", "group6CompBypass", "group6CompThresholdDb", "group6CompRatio", "group6CompAttack", "group6CompRelease", "group6SatBypass", "group6SatDrive", "group6DuckAmountDb", "group6DuckThreshold", "group6DuckAttack", "group6DuckRelease"}},
    {label = "FX_B", controls = {"groupLevel7", "group7PosX", "group7PosY", "group7Width", "group7SpatialBypass", "group7Mute", "group7EqBypass", "group7EqLowDb", "group7EqLowHz", "group7EqLowMidDb", "group7EqLowMidHz", "group7EqHighMidDb", "group7EqHighMidHz", "group7EqHighDb", "group7EqHighHz", "group7CompBypass", "group7CompThresholdDb", "group7CompRatio", "group7CompAttack", "group7CompRelease", "group7SatBypass", "group7SatDrive", "group7DuckAmountDb", "group7DuckThreshold", "group7DuckAttack", "group7DuckRelease"}},
    {label = "RECORDING", controls = {"recordStart", "recordStop", "recorderState", "recorderElapsedSeconds", "recorderSegment", "recorderRemainingSeconds", "recorderDiskFreeBytes", "recorderDroppedFrames", "recorderError"}},
    {label = "PROTECTED TEST GENERATOR", controls = {"testGeneratorEnable", "testGeneratorArm", "testGeneratorLevelDb", "testGeneratorType", "testGeneratorDestination"}},
    {label = "INPUT 1: drums_1", controls = {"input0Group", "input0Partner", "input0Mode", "input0Orientation", "source0Trim", "source0Mute", "source0Polarity", "source0HPF", "source0HPFHz", "source0Pan"}},
    {label = "INPUT 2: drums_2", controls = {"input1Group", "input1Partner", "input1Mode", "input1Orientation", "source1Trim", "source1Mute", "source1Polarity", "source1HPF", "source1HPFHz", "source1Pan"}},
    {label = "INPUT 3: drums_3", controls = {"input2Group", "input2Partner", "input2Mode", "input2Orientation", "source2Trim", "source2Mute", "source2Polarity", "source2HPF", "source2HPFHz", "source2Pan"}},
    {label = "INPUT 4: drums_4", controls = {"input3Group", "input3Partner", "input3Mode", "input3Orientation", "source3Trim", "source3Mute", "source3Polarity", "source3HPF", "source3HPFHz", "source3Pan"}},
    {label = "INPUT 5: bass", controls = {"input4Group", "input4Partner", "input4Mode", "input4Orientation", "source4Trim", "source4Mute", "source4Polarity", "source4HPF", "source4HPFHz", "source4Pan"}},
    {label = "INPUT 6: instruments_1", controls = {"input5Group", "input5Partner", "input5Mode", "input5Orientation", "source5Trim", "source5Mute", "source5Polarity", "source5HPF", "source5HPFHz", "source5Pan"}},
    {label = "INPUT 7: instruments_2", controls = {"input6Group", "input6Partner", "input6Mode", "input6Orientation", "source6Trim", "source6Mute", "source6Polarity", "source6HPF", "source6HPFHz", "source6Pan"}},
    {label = "INPUT 8: instruments_3", controls = {"input7Group", "input7Partner", "input7Mode", "input7Orientation", "source7Trim", "source7Mute", "source7Polarity", "source7HPF", "source7HPFHz", "source7Pan"}},
    {label = "INPUT 9: instruments_4", controls = {"input8Group", "input8Partner", "input8Mode", "input8Orientation", "source8Trim", "source8Mute", "source8Polarity", "source8HPF", "source8HPFHz", "source8Pan"}},
    {label = "INPUT 10: vocals_1", controls = {"input9Group", "input9Partner", "input9Mode", "input9Orientation", "source9Trim", "source9Mute", "source9Polarity", "source9HPF", "source9HPFHz", "source9Pan"}},
    {label = "INPUT 11: vocals_2", controls = {"input10Group", "input10Partner", "input10Mode", "input10Orientation", "source10Trim", "source10Mute", "source10Polarity", "source10HPF", "source10HPFHz", "source10Pan"}},
    {label = "INPUT 12: vocals_3", controls = {"input11Group", "input11Partner", "input11Mode", "input11Orientation", "source11Trim", "source11Mute", "source11Polarity", "source11HPF", "source11HPFHz", "source11Pan"}},
    {label = "INPUT 13: fx_return_1", controls = {"input12Group", "input12Partner", "input12Mode", "input12Orientation", "source12Trim", "source12Mute", "source12Polarity", "source12HPF", "source12HPFHz", "source12Pan"}},
    {label = "INPUT 14: fx_return_2", controls = {"input13Group", "input13Partner", "input13Mode", "input13Orientation", "source13Trim", "source13Mute", "source13Polarity", "source13HPF", "source13HPFHz", "source13Pan"}},
    {label = "INPUT 15: fx_return_3", controls = {"input14Group", "input14Partner", "input14Mode", "input14Orientation", "source14Trim", "source14Mute", "source14Polarity", "source14HPF", "source14HPFHz", "source14Pan"}},
    {label = "INPUT 16: fx_return_4", controls = {"input15Group", "input15Partner", "input15Mode", "input15Orientation", "source15Trim", "source15Mute", "source15Polarity", "source15HPF", "source15HPFHz", "source15Pan"}},
  }
}
