#!/bin/sh
set -u

case "$1" in
  start)
    rm -f /run/af-packet-ready /run/sysv-ipc-ready
    if timeout 5 /usr/bin/sc-adat-kernel-probes >/var/log/kernel-probes.log 2>&1; then
      touch /run/af-packet-ready /run/sysv-ipc-ready
      /usr/bin/sc-adat-progress 'AF_PACKET socket: PASS'
      /usr/bin/sc-adat-progress 'SysV semaphore creation: PASS'
    else
      /usr/bin/sc-adat-progress 'AF_PACKET/SysV kernel probes: FAIL'
    fi
    ;;
  stop) : ;;
  *) exit 2 ;;
esac
