protocol_version=1
expected_synthdefs=sc_adat_tone24.scsyndef,sc_adat_scan.scsyndef,sc_adat_router.scsyndef,sc_adat_group.scsyndef,sc_adat_stereo_group.scsyndef,sc_adat_quad_master.scsyndef,sc_adat_stereo_master.scsyndef,sc_adat_test_generator.scsyndef
